backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "input/assets/Images" # Media files will be stored in the repo under input/assets/Images
public_folder: "../assets/Images" # public_folder indicates where they can be found in the published site. This path is used in image src attributes and is relative to the file where its called.  https://www.netlifycms.org/docs/add-to-your-site/

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    identifier_field: Title
    label: "Blog" # Used in the UI
    folder: "input/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Author", name: "Author", widget: "string"}
      - {label: "Lead", name: "Lead", widget: "string", optional: true, required: false}
      - {label: "Published", name: "Published", widget: "datetime"}
      - {label: "Featured Image", name: "Image", widget: "image", optional: true, required: false}
      - label: Tags
        name: Tags
        widget: list
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "service" # Used in routes, e.g., /admin/collections/blog
    label: "Service" # Used in the UI
    folder: "input/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "Author", widget: "string"}
      - {label: "Lead", name: "Lead", widget: "string", optional: true, required: false}
      - {label: "Published", name: "Published", widget: "datetime"}
      - {label: "Featured Image", name: "Image", widget: "image", optional: true, required: false}
      - label: Tags
        name: Tags
        widget: list
      - label: "City"
        name: "city"
        required: true
        widget: "select"
        default: ""
        options: ["Kraków", "Warszawa (Warsaw)", "Gdańsk"]
      - label: "District"
        name: "district"
        required: true
        widget: "select"
        default: "Centrum"
        options: ["Bronowice", "Kazimierz", "Centrum"]
      - label: "Service"
        name: "service"
        required: true
        widget: "select"
        default: "Car"
        options: ["Hair", "Car", "Food"]
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "survey" # Used in routes, e.g., /admin/collections/blog
    label: "Survey" # Used in the UI
    folder: "input/surveys" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "Author", widget: "string"}
      - {label: "Lead", name: "Lead", widget: "string", optional: true, required: false}
      - {label: "Published", name: "Published", widget: "datetime"}
      - {label: "Featured Image", name: "Image", widget: "image", optional: true, required: false}
      - label: Tags
        name: Tags
        widget: list
      - {label: "Body", name: "body", widget: "markdown"}
